package com.hyrt.cei.vo;



/**
 * AbstractMwpmSysOrginfo generated by MyEclipse - Hibernate Tools
 */

public class MwpmSysKeyword  implements java.io.Serializable {


    // Fields    

     private String id;
     private String keyword;

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

	public String getKeyword() {
		return keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}


	




}