package com.hyrt.cei.vo;



/**
 * MwpmDictSystemtype generated by MyEclipse Persistence Tools
 */

public class MwpmDictSystemtype implements java.io.Serializable {

	// Fields

	private String id;

	private String name;
	private String code;
	private String status;

	// Constructors

	/** default constructor */
	public MwpmDictSystemtype() {
	}
    


	public MwpmDictSystemtype(String name, String code, String status) {
		super();
		this.name = name;
		this.code = code;
		this.status = status;
	}



	/** full constructor */
	public MwpmDictSystemtype(String type) {
		this.name = type;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	

	public String getName() {
		return name;
	}



	public void setName(String name) {
		this.name = name;
	}



	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}