package com.hyrt.cei.vo;



/**
 * AbstractMwpmDictDutyinfo generated by MyEclipse - Hibernate Tools
 */

public class MwpmDictDutyinfo  implements java.io.Serializable {


    // Fields    

     private String id;
     private String code;
     private String name;
     private String status;

     
   
    // Property accessors

   

	public MwpmDictDutyinfo(String code, String name, String status) {
		super();
		this.code = code;
		this.name = name;
		this.status = status;
	}

	public MwpmDictDutyinfo() {
		
	}

	public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
   








}