package com.hyrt.cei.vo;

import java.util.Date;



/**
 * MwpmDictSystemtype generated by MyEclipse Persistence Tools
 */

public class MwpmSysUpdateloadPackage implements java.io.Serializable {

	// Fields

	private String id;

	private String editionnum;
	private String packagename;
	private String type;
	private Date createdate;
	private String submit;
	private String isupdate;

	// Constructors

	/** default constructor */
	public MwpmSysUpdateloadPackage() {
	}
    


	public MwpmSysUpdateloadPackage(String editionnum, String packagename, 
			String type,Date createdate,String submit,String isupdate) {
		super();
		this.editionnum = editionnum;
		this.packagename = packagename;
		this.type = type;
		this.createdate = createdate;
		this.submit = submit;
		this.isupdate = isupdate;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getEditionnum() {
		return editionnum;
	}

	public void setEditionnum(String editionnum) {
		this.editionnum = editionnum;
	}

	public String getPackagename() {
		return packagename;
	}

	public void setPackagename(String packagename) {
		this.packagename = packagename;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Date getCreatedate() {
		return createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public String getSubmit() {
		return submit;
	}

	public void setSubmit(String submit) {
		this.submit = submit;
	}

	public String getIsupdate() {
		return isupdate;
	}

	public void setIsupdate(String isupdate) {
		this.isupdate = isupdate;
	}




}